name: "Bug Report"
description: "Report a bug"
title: "[BUG] "
labels: ["bug"]

body:
  - type: input
    id: name
    attributes:
      label: "Name"
      description: "The name of the bug"
      placeholder: "Bug name"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "The version of the project"
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Expected & Actual behavior, Steps to reproduce, Screenshots, etc."
      placeholder: "Describe the bug in detail"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant log output"
      description: "Paste logs here"
      render: shell
    validations:
      required: false
