- type: input
  id: name
  attributes:
      label: Name
      description: The name of the bug
      placeholder: Bug name
  validations:
      required: true

- type: input
  id: version
  attributes:
      label: Version
      description: The version of the project
      placeholder: v1.0.0
  validations:
      required: true

- type: markdown
  attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Excepted & Actual behavior, Steps to reproduce, Screenshots, etc.
  validations:
      required: true

- type: textarea
  id: logs
  attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  validations:
      required: false

