name: Security Check

on:
    push:
        branches: [main]
    pull_request:

jobs:
    check-eval:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Fail if eval is used
              run: |
                  if grep -R "eval(" . --exclude-dir=.github; then
                    echo "❌ eval() is not allowed"
                    exit 1
                  fi
